version: '3'
services:
  postgres:
    image: "postgres:latest"
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
    depends_on:
      - postgres
