"""empty message

Revision ID: 0266cc7ab8ed
Revises: c1696a2890d8
Create Date: 2019-11-05 18:01:36.946063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0266cc7ab8ed'
down_revision = 'c1696a2890d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Integer(), nullable=True))
    op.drop_column('user', 'id_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id_admin', sa.INTEGER(), nullable=True))
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
