"""empty message

Revision ID: b0319c006d92
Revises: 0266cc7ab8ed
Create Date: 2019-11-12 10:01:09.605271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0319c006d92'
down_revision = '0266cc7ab8ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=5), nullable=True),
    sa.Column('admin_area', sa.String(length=20), nullable=True),
    sa.Column('sub_admin_area', sa.String(length=20), nullable=True),
    sa.Column('locality', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('thoroughfare', sa.String(length=25), nullable=True),
    sa.Column('premise', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('death_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('culture', sa.String(length=35), nullable=True),
    sa.Column('lang_code', sa.String(length=5), nullable=True),
    sa.Column('lang_name', sa.String(length=35), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publisher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_name', sa.String(length=100), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('wiki_link', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('founded', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('authorship',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('author_id', 'book_id')
    )
    op.create_table('book_subject',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'subject_id')
    )
    op.add_column('book', sa.Column('genre_id', sa.Integer(), nullable=True))
    op.add_column('book', sa.Column('isbn_13', sa.String(length=20), nullable=True))
    op.add_column('book', sa.Column('language_id', sa.Integer(), nullable=True))
    op.add_column('book', sa.Column('msrp', sa.Float(), nullable=True))
    op.add_column('book', sa.Column('publish_date', sa.DateTime(), nullable=True))
    op.add_column('book', sa.Column('publisher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'book', 'genre', ['genre_id'], ['id'])
    op.create_foreign_key(None, 'book', 'language', ['language_id'], ['id'])
    op.create_foreign_key(None, 'book', 'publisher', ['publisher_id'], ['id'])
    op.drop_column('book', 'author')
    op.drop_column('user', 'id_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id_admin', sa.INTEGER(), nullable=True))
    op.add_column('book', sa.Column('author', sa.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'publisher_id')
    op.drop_column('book', 'publish_date')
    op.drop_column('book', 'msrp')
    op.drop_column('book', 'language_id')
    op.drop_column('book', 'isbn_13')
    op.drop_column('book', 'genre_id')
    op.drop_table('book_subject')
    op.drop_table('authorship')
    op.drop_table('publisher')
    op.drop_table('subject')
    op.drop_table('language')
    op.drop_table('genre')
    op.drop_table('author')
    op.drop_table('address')
    # ### end Alembic commands ###
