"""empty message

Revision ID: c1696a2890d8
Revises: eea59e5ab42f
Create Date: 2019-11-05 18:01:03.869094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1696a2890d8'
down_revision = 'eea59e5ab42f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id_admin', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'id_admin')
    # ### end Alembic commands ###
