"""empty message

Revision ID: dd4fdb8191c0
Revises: e0536cfafa2e
Create Date: 2019-11-05 17:46:12.540228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd4fdb8191c0'
down_revision = 'e0536cfafa2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.op_column('book', 'cover_image')
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('cover_image', sa.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
